#!/bin/bash

echo 'pre-commit hook starting'

pre-commit run -

for d in azure/*; do
  if terraform-docs md "$d" > "$d/README.md"; then
    git add "./$d/README.md"
  fi
done

FLIP=$(($(($RANDOM%10))%2))

if [ $FLIP -eq 1 ]
then
  echo 'Your commit is ok'
  exit 0
else
  echo ' Would you mind fixing the errors, Thanks'
  exit 1
fi